//! Compile-time-safe ROM bank switching for the Game Boy.
//!
//! Game Boy cartridges larger than 32 KiB can only map one 16 KiB **ROM bank**
//! at a time into the `0x4000..0x8000` window; code or data in any other bank is
//! simply not addressable until that bank is switched in. Getting this wrong
//! (holding a pointer into a bank that is no longer mapped) is a classic source
//! of corruption. This crate moves the check to compile time.
//!
//! The model is borrowed from [GhostCell]: the *permission* is separated from
//! the *data*, and a brand type ties them together.
//!
//! - A [`Bank<G>`] is a zero-sized token: a witness that group `G`'s bank is
//!   currently mapped.
//! - A [`Far<T, G>`] is a pointer to a `T` living in group `G`'s bank. It cannot
//!   be read without a [`Bank<G>`](Bank).
//! - [`scope`] switches into a bank, lends you the token for the duration of a
//!   closure, then restores the previous bank. Because the token is borrowed
//!   `&mut` across the switch, a live reference into a bank can never outlive a
//!   switch away from it; the borrow checker rejects it.
//!
//! For dynamic dispatch across banks chosen at runtime, [`DynFar<T>`] erases the
//! group to a runtime bank number, and [`Warp`] is a deferred banked call: the
//! analog of a [`Future`], produced by a banked function and executed with
//! [`Warp::drive`].
//!
//! [GhostCell]: https://plv.mpi-sws.org/rustbelt/ghostcell/
//!
//! # Examples
//!
//! ```ignore
//! use gb_bank::*;
//!
//! // A bank group. (Normally generated by the `#[bank]` macro; shown raw here.)
//! struct Sound;
//! impl Group for Sound {
//!     const FIXED: bool = false;
//!     fn bank() -> u8 { 2 }
//! }
//!
//! fn main_loop(anchor: Anchor, bank: &mut Bank<GroupZero>) {
//!     // Enter Sound's bank for a block; `b` witnesses that it is mapped.
//!     scope(anchor, bank, |b: &mut Bank<Sound>| {
//!         let tempo = *b.local(&TEMPO);   // read banked data, no extra switch
//!         // ... use `tempo` while still inside Sound's bank ...
//!     });
//!     // Sound's bank is restored to the caller's on the way out.
//! }
//! ```
//!
//! # Panics, unwinding, and interrupts
//!
//! The bank restore in [`scope`] (and the [`Far`] call / borrow paths) runs *after*
//! the closure returns, so an unwinding panic would skip it and leave the wrong
//! bank mapped. This is sound on the Game Boy because the target aborts on panic
//! (there is no unwinder), so a panic never resumes into a stale-bank token. These
//! types are not designed to be unwind-safe on a hosted, unwinding target.
//!
//! The safety model also assumes that nothing changes the mapped bank *behind the
//! token's back*. An interrupt handler that switches banks (e.g. to read banked
//! data) must save [`current_bank`] on entry and restore it before returning, so the
//! interrupted code resumes with the bank its live token still claims is mapped. An
//! ISR that is not bank-transparent breaks the invariant, just like a raw
//! [`switch_bank`] that is not paired with a matching restore.


use core::{any::TypeId, marker::PhantomData};

mod far;
mod warp;

pub use far::{DynFar, Far, FarCall, FarWith};
pub use warp::{Warp, BankedWarp, FixedFn, FixedWarp, BankSafe};

// ===== Low-level bank switch =====

// The software bank shadow. The MBC bank register is write-only, so the mapped
// bank is tracked here: a High RAM cell read and written with the immediate `ldh`
// form through gb-hram. The runtime zero-initialises HRAM at reset (as gb-hram
// requires), so it starts at 0. The `as "_current_bank"` exports the storage as
// the `__current_bank` symbol that GBDK's C runtime also references (the target
// adds the leading underscore).
use gb_hram::prelude::*;

gb_hram::hram! {
    static CURRENT_BANK as "_current_bank": HramAtomicCell<u8>;
}

/// Switch the active ROM bank.
///
/// Writes both the MBC bank register at `0x2000` (write-only on hardware) and the
/// software bank shadow that interrupt handlers rely on to save and restore the
/// mapped bank. Only `0x2000` is written, so MBC5 banks 256 and up, which also
/// need the register at `0x3000`, are out of reach.
///
/// Prefer the safe [`scope`] / [`Far`] API; this is the raw primitive for hand
/// rolled control. After calling it, use [`Bank::assume`] to mint a matching
/// token.
///
/// # Safety
///
/// `bank` must be a valid bank for the cartridge's MBC, and the caller is
/// responsible for restoring the previous bank and for any pointers that become
/// invalid across the switch.
///
/// MBC1, MBC2, and MBC3 read a written `0` as `1`, so `switch_bank(0)` maps bank 1
/// there while the shadow records 0, and an interrupt would restore the wrong bank.
/// Only MBC5 maps bank 0 into the window.
#[inline(never)]
pub unsafe fn switch_bank(bank: u8) {
    // Shadow (immediate `ldh` via gb-hram), then the write-only MBC register.
    CURRENT_BANK.set(bank);
    unsafe { core::ptr::write_volatile(0x2000 as *mut u8, bank) };
}

/// Read the currently mapped bank from the software shadow.
///
/// The MBC register is write-only, so the active bank cannot be read from
/// hardware; this returns the shadow maintained by [`switch_bank`]. Intended for
/// interrupt save/restore; the normal call path restores via the caller's group
/// type and never needs it.
#[inline]
pub fn current_bank() -> u8 {
    CURRENT_BANK.get()
}

// ===== Group brands =====

/// The compile-time identity of a bank group.
///
/// The implementing type *is* the brand: two values share a group iff they share
/// the type parameter `G`, checked entirely at compile time. The runtime
/// [`bank()`](Group::bank) number is only consulted for the actual hardware
/// switch.
///
/// Groups are normally generated by the `#[bank]` macro, one per banked module.
pub trait Group: 'static {
    /// Whether this group is permanently mapped, so switching to it is a no-op.
    ///
    /// `true` only for [`GroupZero`] (bank 0).
    const FIXED: bool;

    /// The physical bank number, resolved at link time by gb-bank-pack.
    fn bank() -> u8;
}

/// Bank 0: the always-mapped region.
///
/// Switching to or from a [`FIXED`](Group::FIXED) group is elided, so calls and
/// data accesses anchored at `GroupZero` never touch the MBC register.
pub struct GroupZero;

impl Group for GroupZero {
    const FIXED: bool = true;
    #[inline(always)]
    fn bank() -> u8 {
        0
    }
}

// ===== Bank token + scope =====

/// A witness that group `G`'s bank is currently mapped.
///
/// This is the GhostCell-style permission token: a zero-sized value whose type
/// `G` is the brand. Borrowing it shared ([`local`](Far::local)) yields references
/// into the bank; borrowing it `&mut` (a switch via [`scope`]) is what changes
/// the mapping. Because you cannot do both at once, a reference obtained from
/// `local` can never be live across a switch; the conflict is a borrow error.
///
/// The token is `!Send` and only mintable through [`assume`](Bank::assume) (or,
/// safely, the closure argument of [`scope`]).
///
/// # Examples
///
/// ```ignore
/// # use gb_bank::*;
/// # struct Sound; impl Group for Sound { const FIXED: bool = false; fn bank() -> u8 { 2 } }
/// fn play(b: &mut Bank<Sound>) {
///     let note = *b.local(&MELODY);   // `b` proves Sound is mapped
///     // ...
/// }
/// ```
///
/// The token is `!Send`: a "this bank is mapped" proof cannot cross threads.
///
/// ```compile_fail
/// # use gb_bank::*;
/// fn assert_send<T: Send>() {}
/// assert_send::<Bank<GroupZero>>(); // ERROR: Bank is !Send
/// ```
pub struct Bank<G: Group> {
    _bank: PhantomData<G>,
    _not_send: PhantomData<*const ()>,
}

impl<G: Group> Bank<G> {
    /// Mint a token, asserting that group `G`'s bank is already mapped.
    ///
    /// This is the escape hatch for hand-rolled control: after a raw
    /// [`switch_bank`] or inline asm, call `assume` to re-enter the safe
    /// [`local`](Far::local) / [`scope`] API.
    ///
    /// # Safety
    ///
    /// Group `G`'s bank must actually be mapped at the call site; otherwise every
    /// subsequent `local`/call through this token reads the wrong bank.
    #[inline(always)]
    pub const unsafe fn assume() -> Self {
        Bank {
            _bank: PhantomData,
            _not_send: PhantomData,
        }
    }

}

/// Proof that the holder runs in bank 0 (the always-mapped region), and
/// so may run a closure across a bank switch via [`scope`] / [`there`](FarWith::there).
///
/// Those operations lend a closure across a switch; the closure's *code* must stay
/// mapped while it runs, which only holds for code in bank 0. An `Anchor` is that
/// guarantee, as a zero-sized [`Copy`] capability. The `#[bank::main]` and
/// `#[bank::zero]` macros mint one at the top of every body (their code is
/// in bank 0); a `#[bank]` function gets none, so it cannot reach `scope` / `there`,
/// which would otherwise run a banked closure the switch unmaps.
///
/// Being `Copy`, it threads into nested scopes without borrow friction.
#[derive(Clone, Copy)]
pub struct Anchor(());

// An `Anchor` witnesses that the *current* code is in bank 0, so carrying one into a
// banked call would falsify it: the callee would hold a bank-0 capability while
// running from a switchable bank.
impl !BankSafe for Anchor {}

impl Anchor {
    /// Assert that the calling code runs in bank 0.
    ///
    /// # Safety
    ///
    /// The caller must physically reside in bank 0 (the always-mapped region): a
    /// `#[bank::main]` / `#[bank::zero]` body, or a plain `fn` the linker keeps
    /// in bank 0. A `#[bank]` function is *not* in bank 0 and must never mint one.
    ///
    /// An `Anchor` must also not be moved into `#[bank]` code: it witnesses that the
    /// *current* code is in bank 0, which carrying it into a banked function would
    /// falsify. (Safe code cannot do this: the macro-minted `Anchor` is hygienic and
    /// there is no other safe constructor.)
    #[inline(always)]
    pub const unsafe fn assume() -> Self {
        Anchor(())
    }
}

/// Enter group `G`'s bank for the duration of `f`, then restore the caller (`C`).
///
/// This is the safe heart of the crate. It switches to `G`, hands `f` a fresh
/// [`Bank<G>`] token, runs it, and switches back to `C`. Threading the caller's
/// `&mut Bank<C>` is what makes the cross-bank footgun a compile error: a
/// reference borrowed from one token cannot survive a nested [`scope`] that needs
/// the same token `&mut`.
///
/// The switch is elided entirely when `G` is [`FIXED`](Group::FIXED) or `C == G`
/// (same group, folded at compile time), so same-bank work costs nothing.
///
/// # Examples
///
/// ```ignore
/// # use gb_bank::*;
/// # struct Sound; impl Group for Sound { const FIXED: bool = false; fn bank() -> u8 { 2 } }
/// fn run(anchor: Anchor, bank: &mut Bank<GroupZero>) {
///     let first = scope(anchor, bank, |b: &mut Bank<Sound>| *b.local(&MELODY).first().unwrap());
///     // back in the caller's bank here
/// }
/// ```
///
/// The borrow checker stops a banked reference from escaping the switch:
///
/// ```compile_fail
/// # use gb_bank::*;
/// # struct G; impl Group for G { const FIXED: bool = false; fn bank() -> u8 { 1 } }
/// fn leak<'a>(anchor: Anchor, bank: &mut Bank<GroupZero>, data: &'a Far<u8, G>) -> &'a u8 {
///     scope(anchor, bank, |g| g.local(data)) // ERROR: the ref borrows the inner token
/// }
/// ```
#[inline]
pub fn scope<C: Group, G: Group, R: BankSafe>(
    _anchor: Anchor,
    outer: &mut Bank<C>,
    f: impl FnOnce(&mut Bank<G>) -> R,
) -> R {
    switch_run(outer, f)
}

/// The bank-switch primitive behind [`scope`] and the one-shot [`Warp::drive`] /
/// [`FarCall::invoke`]: switch to `G`, run `f`, restore `C`, eliding when `G` is
/// [`FIXED`](Group::FIXED) or `C == G`.
///
/// Unlike [`scope`] it takes no [`Anchor`], so it stays crate-internal: its callers
/// either thread an `Anchor` through (`scope` / [`there`](FarWith::there), whose `f`
/// is a user closure) or run no user closure at all (`drive` / `invoke` call the
/// banked function themselves, taking [`switch_run_far`] when the caller is banked).
#[inline]
pub(crate) fn switch_run<C: Group, G: Group, R>(
    _outer: &mut Bank<C>,
    f: impl FnOnce(&mut Bank<G>) -> R,
) -> R {
    if G::FIXED || const { TypeId::of::<C>() == TypeId::of::<G>() } {
        let mut b = unsafe { Bank::<G>::assume() };
        f(&mut b)
    } else {
        unsafe { switch_bank(G::bank()) };
        let mut b = unsafe { Bank::<G>::assume() };
        let r = f(&mut b);
        if !C::FIXED {
            unsafe { switch_bank(C::bank()) };
        }
        r
    }
}

/// [`switch_run`] for a caller that is itself banked, whose code leaves the window
/// during the call: `#[inline(never)]` keeps the switch in a bank-0 trampoline.
#[inline(never)]
pub(crate) fn switch_run_far<C: Group, G: Group, R>(
    outer: &mut Bank<C>,
    f: impl FnOnce(&mut Bank<G>) -> R,
) -> R {
    switch_run(outer, f)
}
