[cargo]
target = "sm83-nintendo-none-elf"
features = "all"
cfgs = [
    "debug_assertions",
    "miri",
    "gb_pak_mbc=mbc5",
    "gb_pak_sram",
    "gb_pak_rtc",
    "gb_pak_rumble",
    "gb_pak_tilt",
]
