[package]
name = "gb-bank-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Procedural macros for gb-bank"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = { workspace = true }
syn = { workspace = true, features = ["visit-mut"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
