[build]
rustdocflags = ["--cfg", "docsrs", "-Z", "unstable-options",
    "--extern-html-root-url", "zerocopy=https://docs.rs/zerocopy/0.8"]

# core's `fmt::rt::Argument` is `repr(align(2))`
[target.sm83-nintendo-none-elf]
rustflags = ["-Cllvm-args=-z80-warn-stack-align-padding=2"]

[alias]
doc-all = [
    "doc", "--target", "sm83-nintendo-none-elf", "--all-features", "--no-deps",
    "--config", 'target.sm83-nintendo-none-elf.rustflags=["-Cllvm-args=-z80-warn-stack-align-padding=2","--cfg","gb_pak_sram","--cfg","gb_pak_rtc","--cfg","gb_pak_rumble","--cfg","gb_pak_tilt"]',
    "--config", 'build.rustdocflags=["-Z","unstable-options","--extern-html-root-url","zerocopy=https://docs.rs/zerocopy/0.8","--cfg","docsrs","--cfg","gb_pak_sram","--cfg","gb_pak_rtc","--cfg","gb_pak_rumble","--cfg","gb_pak_tilt"]',
]
